# Site settings
title: Starting from NOW!
description: Blog of Jiale Cheng
baseurl: "" 
url: "https://jiale-cheng.github.io" 

# GitHub User settings
username: Jiale Cheng
github_username: jiale-cheng
user_description: A Ph.D. candidate with interest in information theory, coding and mathematical background of ML with their applications to data privacy/security.
user_title: PhD candidate
email: jaylencheng@outlook.com

# Blog Author settings
author:
  name:           Jiale Cheng
  picture:        
  email:          jlcheng@seu.edu.cn
  description:    Interested in information theory, coding and mathematical background of ML with their applications to data privacy/security.
  twitter:
  facebook:
  github:         https://github.com/Jiale-Cheng
  linkedin:
  # # If you're forking this site, make sure you delete this entry!
  clustrmap:      yX6fKVAPwoN64YALu1NiouBF9fG5nA769GCuOGalMDg 
  # If you're forking this site, make sure you delete this entry!


# markdown
markdown: kramdown

future: true
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: /:year/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.tex"
 - "*.aux"
 - "*.log"
 - "*.out"
 - "*.gz"
 - "*.toc"
 - "*.bib"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
 - "*.source.*"